version: '3.8'

services:
  faka:
    build:
      context: .
      dockerfile: Dockerfile.china
    container_name: faka-app
    ports:
      - "3019:3019"
    volumes:
      - ./instance:/app/instance
      - ./uploads:/app/uploads
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
